import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import {execSync} from 'child_process';
import path from 'path';
import {defineConfig, type Plugin} from 'vite';

/**
 * The production Content-Security-Policy in index.html sets `connect-src 'none'`,
 * which is the app's core privacy guarantee: the browser itself refuses every
 * outbound network request, so photos physically cannot be uploaded.
 *
 * That same rule also blocks the WebSocket the Vite dev server uses for hot
 * module reload. This plugin relaxes ONLY `connect-src`, and ONLY while running
 * `vite dev` (`apply: 'serve'`). It never runs during `vite build`, so the
 * policy shipped to users is identical to the one written in index.html.
 */
function devCspRelax(): Plugin {
  return {
    name: 'cropalot-dev-csp-relax',
    apply: 'serve',
    transformIndexHtml(html) {
      return html.replace("connect-src 'none'", "connect-src 'self' ws: wss:");
    },
  };
}

/**
 * Emits a service worker that precaches this exact build.
 *
 * Written at build time rather than by hand because Vite hashes asset
 * filenames, so the precache list is only knowable once the bundle exists.
 * Being able to reload with no network is what makes the app's offline claim
 * true rather than merely true-until-you-refresh.
 *
 * The strategy is deliberately plain: precache everything on install, serve
 * cache-first afterwards, and drop caches from older builds on activate. The
 * whole app is a handful of files with content-hashed names, so there is
 * nothing here that warrants a framework.
 */
function serviceWorker(): Plugin {
  return {
    name: 'cropalot-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle).map(name => `./${name}`);
      const precache = ['./', './index.html', './manifest.webmanifest', './favicon.png', ...assets];
      const version = `${resolveCommitSha().slice(0, 12)}-${Date.now()}`;

      const source = `// Generated by vite.config.ts at build time. Do not edit.
const CACHE = 'cropalot-${version}';
const PRECACHE = ${JSON.stringify([...new Set(precache)], null, 2)};

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first: this build's assets never change, so a hit is always correct and
// the app opens with no network at all. A new deploy ships a new cache name.
self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request).then(hit => {
      if (hit) return hit;
      return fetch(request)
        .then(response => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then(cache => cache.put(request, copy));
          }
          return response;
        })
        .catch(() =>
          // Offline and not precached: serve the app shell so a deep reload
          // still opens rather than showing the browser's error page.
          request.mode === 'navigate' ? caches.match('./index.html') : Promise.reject()
        );
    })
  );
});
`;

      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    }
  };
}

/**
 * Records the commit this bundle was built from, so the running app can state
 * its own provenance instead of merely asserting trustworthiness. Falls back to
 * 'unknown' outside a git checkout (e.g. a source tarball build).
 */
function resolveCommitSha(): string {
  if (process.env.GITHUB_SHA) return process.env.GITHUB_SHA;
  try {
    return execSync('git rev-parse HEAD', {stdio: ['ignore', 'pipe', 'ignore']})
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

export default defineConfig(() => {
  return {
    base: './',
    plugins: [react(), tailwindcss(), devCspRelax(), serviceWorker()],
    define: {
      __COMMIT_SHA__: JSON.stringify(resolveCommitSha()),
      __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
    },
    build: {
      // Vite's module-preload polyfill is injected as an inline <script>, which
      // `script-src 'self'` correctly refuses. Every browser this app targets
      // supports module preload natively, so the polyfill is redundant.
      modulePreload: {polyfill: false},
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modify—file watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
      // Disable file watching when DISABLE_HMR is true to save CPU during agent edits.
      watch: process.env.DISABLE_HMR === 'true' ? null : {},
    },
  };
});
